'use strict';

var jsdom = require('jsdom');
var path = require('node:path');

const defaultOptions = {
    rootDirectory: null,
    moduleGroups: [],
};

/**
 * Render function that generates an HTML string based on a given input.
 * @callback renderer
 * @param {Object} jsonObjects - JSON arrays imported from .JSON files specified by
 * options.moduleGroups[].jsonPaths
 * @param {Object} config - input VITE defineConfig data.
 * @returns {HTML} - Generated output HTML string.
 */

/**
 * Vite plugin that prerenders HTML generated by JS functions to the DOM during
 * build time and run time.
 *
 *
 *
 *
 * @param {Object} inputOptions - Settings to configure prerenderer plugin.
 * @param {import("fs").PathLike} [inputOptions.rootDirectory] - Path to root directory,
 * if different from config.root.
 * @param {Object[]} inputOptions.moduleGroups - Input modules for each render function
 * and their specific configurations.
 *
 *
 * @param {renderer} options.moduleGroups[].renderFunction - Callback function that
 * generates the replacement HTML to be added to the DOM.
 * @param {string} options.moduleGroups[].selector - The targeted querySelector to be
 * replaced by the newly generated HTML.
 * @param {string|string[]} options.moduleGroups[].dataModules - Vite module imports to be
 * used as the inputs to the generator functions.
 * @param {string|string[]} [options.moduleGroups[].pathIsolate] - File path or array of
 * file paths to isolate render function to. Root directory matches that of the root
 * directory in vite.config.js.
 * @param {string|string[]} [options.moduleGroups[].pathIgnore] - File path or array of
 * file paths to isolate render function to. Root directory matches that of the root
 * directory in vite.config.js.
 * @param {Boolean} [options.moduleGroups[].outer = false] - Boolean value that determines
 * whether to replace the outerHTML or the innerHTML of the DOM node.
 *
 *
 * @returns {import("vite").Plugin} - Vite plugin object.
 */
function viteVanillaPrerenderer(inputOptions = {}) {
    const options = { ...defaultOptions, ...inputOptions };

    const { moduleGroups, rootDirectory, pathsIgnore = [] } = options;

    let viteServer;
    let resolveId;
    let loadModule;
    const watchedJsonFiles = new Set();

    let command;
    let root;

    return {
        name: "vite-plugin-html-prerenderer",
        enforce: "post",
        configResolved(resolvedConfig) {
            ({ command } = resolvedConfig);
            root = rootDirectory || resolvedConfig.root;
        },
        configureServer(server) {
            viteServer = server;

            server.watcher.on("change", (file) => {
                const normalizedFile = path.normalize(file);

                if (!watchedJsonFiles.has(normalizedFile)) return;

                console.log(
                    `\n[vite-plugin-html-prerenderer] Watched JSON file changed: ${path.basename(
                        file
                    )}. Restarting server...`
                );
                try {
                    server.restart();
                } catch (error) {
                    console.error(
                        `[vite-plugin-html-prerenderer] Error restarting server: ${error.message}`
                    );
                }
            });
        },
        buildStart() {
            [resolveId, loadModule] = [this.resolve, this.load];
        },
        async transformIndexHtml(html, context) {
            if (moduleGroups.length === 0) return html;
            const { path: contextPath } = context;
            if (
                pathsIgnore.some((filePath) => contextPath.startsWith(filePath))
            )
                return html;

            const config = { root, command };

            const loadModuleData = loadModuleDataCurry(
                config,
                viteServer,
                {
                    resolve: resolveId,
                    load: loadModule,
                },
                watchedJsonFiles
            );

            const prerenderModule = prerenderModuleCurry(contextPath);

            const dom = new jsdom.JSDOM(html);
            const { document } = dom.window;

            const previousDocument = globalThis.document;
            globalThis.document = document;

            try {
                for (const moduleGroup of moduleGroups) {
                    const { dataModules } = moduleGroup;
                    if (!dataModules) {
                        await prerenderModule(moduleGroup);
                        continue;
                    }
                    const dataModulePathArray = Array.isArray(dataModules)
                        ? dataModules
                        : [dataModules];

                    const dataModulePromises =
                        dataModulePathArray.map(loadModuleData);

                    const dataEntries = await Promise.all(dataModulePromises);

                    const loadedData = Object.fromEntries(
                        dataEntries.filter((entry) => entry[1] !== null)
                    );

                    await prerenderModule(moduleGroup, loadedData);
                }
            } finally {
                globalThis.document = previousDocument;
            }

            return dom.serialize();
        },
    };
}

function loadModuleDataCurry(
    config,
    viteServer,
    pluginContext,
    watchedJsonFiles
) {
    return async (moduleId) => {
        const key = path.basename(moduleId).split(".")[0];
        const isVirtual = moduleId.startsWith("\0");
        const isFilePath = moduleId.includes(path.sep);
        const isJsonModule =
            moduleId.endsWith(".json") && !isVirtual && isFilePath;

        const pathResolvedModule = isJsonModule
            ? path.resolve(config.root, moduleId)
            : moduleId;

        if (config.command === "serve" && isJsonModule) {
            watchedJsonFiles.add(pathResolvedModule);
        }

        try {
            if (config.command === "serve") {
                const module = await viteServer.ssrLoadModule(
                    pathResolvedModule
                );

                const data = module.default || module;
                return [key, data];
            }

            const pluginResolvedModule = await pluginContext.resolve(
                pathResolvedModule
            );

            if (!pluginResolvedModule) return [key, null];

            const loadedModule = await pluginContext.load({
                id: pluginResolvedModule.id,
            });

            const module = await import(
                `data:text/javascript,${encodeURIComponent(loadedModule.code)}`
            );

            const data = module.default || module;
            return [key, data];
        } catch (error) {
            console.error(
                `[vite-plugin-html-prerenderer] ⚠️ Failed to load module ${moduleId}:`,
                error
            );
        }

        return [key, null];
    };
}

function prerenderModuleCurry(contextPath) {
    return async (moduleGroup, jsonObjects = {}) => {
        const { renderFunction, selector, ...options } = moduleGroup;
        const { outer, pathIgnore, pathIsolate } = options;

        if (typeof renderFunction !== "function" || !selector) return;

        const isolatePaths = Array.isArray(pathIsolate)
            ? pathIsolate.filter(Boolean)
            : [pathIsolate].filter(Boolean);
        const ignorePaths = Array.isArray(pathIgnore)
            ? pathIgnore.filter(Boolean)
            : [pathIgnore].filter(Boolean);

        const isPathToIsolate = pathIsolate
            ? pathMatches(contextPath, isolatePaths)
            : true;
        const isPathToIgnore = pathIgnore
            ? pathMatches(contextPath, ignorePaths)
            : false;

        if (isPathToIgnore || !isPathToIsolate) return;

        const elements = document.querySelectorAll(selector);

        if (elements.length === 0) return;

        for (const element of elements) {
            const result = await Promise.resolve(renderFunction(jsonObjects));
            if (outer) element.outerHTML = result;
            else element.innerHTML = result;
        }
    };
}

function pathMatches(contextPath, pathsArray) {
    return contextPath && pathsArray
        ? pathsArray.some(
              (filePath) =>
                  contextPath.startsWith(filePath) || contextPath === filePath
          )
        : false;
}

module.exports = viteVanillaPrerenderer;
